# Generated by Django 4.2.7 on 2023-11-24 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 15, 33, 23, 602816)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 15, 33, 23, 602810)),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 15, 33, 23, 603000)),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 15, 33, 23, 602996)),
        ),
        migrations.AlterField(
            model_name='product',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 15, 33, 23, 602578)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 15, 33, 23, 602568)),
        ),
    ]
