# Generated by Django 4.2.7 on 2023-11-24 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_order_creation_alter_order_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 15, 38, 30, 544475)),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 15, 38, 30, 544470)),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 15, 38, 30, 544652)),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 15, 38, 30, 544647)),
        ),
        migrations.AlterField(
            model_name='product',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 15, 38, 30, 544251)),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 15, 38, 30, 544243)),
        ),
    ]
